// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geoservice.proto

package io.grpc.geoservice;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code geoservice.InPolygonRequest}
 */
public  final class InPolygonRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:geoservice.InPolygonRequest)
    InPolygonRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InPolygonRequest.newBuilder() to construct.
  private InPolygonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InPolygonRequest() {
    polygon_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InPolygonRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.grpc.geoservice.InPolygonRequest.Point.Builder subBuilder = null;
            if (point_ != null) {
              subBuilder = point_.toBuilder();
            }
            point_ = input.readMessage(io.grpc.geoservice.InPolygonRequest.Point.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(point_);
              point_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              polygon_ = new java.util.ArrayList<io.grpc.geoservice.InPolygonRequest.Point>();
              mutable_bitField0_ |= 0x00000002;
            }
            polygon_.add(
                input.readMessage(io.grpc.geoservice.InPolygonRequest.Point.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        polygon_ = java.util.Collections.unmodifiableList(polygon_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.geoservice.InPolygonRequest.class, io.grpc.geoservice.InPolygonRequest.Builder.class);
  }

  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:geoservice.InPolygonRequest.Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float lat = 1;</code>
     */
    float getLat();

    /**
     * <code>float lng = 2;</code>
     */
    float getLng();
  }
  /**
   * Protobuf type {@code geoservice.InPolygonRequest.Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:geoservice.InPolygonRequest.Point)
      PointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              lat_ = input.readFloat();
              break;
            }
            case 21: {

              lng_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_Point_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.geoservice.InPolygonRequest.Point.class, io.grpc.geoservice.InPolygonRequest.Point.Builder.class);
    }

    public static final int LAT_FIELD_NUMBER = 1;
    private float lat_;
    /**
     * <code>float lat = 1;</code>
     */
    public float getLat() {
      return lat_;
    }

    public static final int LNG_FIELD_NUMBER = 2;
    private float lng_;
    /**
     * <code>float lng = 2;</code>
     */
    public float getLng() {
      return lng_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lat_ != 0F) {
        output.writeFloat(1, lat_);
      }
      if (lng_ != 0F) {
        output.writeFloat(2, lng_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, lat_);
      }
      if (lng_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, lng_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.geoservice.InPolygonRequest.Point)) {
        return super.equals(obj);
      }
      io.grpc.geoservice.InPolygonRequest.Point other = (io.grpc.geoservice.InPolygonRequest.Point) obj;

      if (java.lang.Float.floatToIntBits(getLat())
          != java.lang.Float.floatToIntBits(
              other.getLat())) return false;
      if (java.lang.Float.floatToIntBits(getLng())
          != java.lang.Float.floatToIntBits(
              other.getLng())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLat());
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLng());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.geoservice.InPolygonRequest.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.geoservice.InPolygonRequest.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code geoservice.InPolygonRequest.Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:geoservice.InPolygonRequest.Point)
        io.grpc.geoservice.InPolygonRequest.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_Point_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.geoservice.InPolygonRequest.Point.class, io.grpc.geoservice.InPolygonRequest.Point.Builder.class);
      }

      // Construct using io.grpc.geoservice.InPolygonRequest.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lat_ = 0F;

        lng_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_Point_descriptor;
      }

      @java.lang.Override
      public io.grpc.geoservice.InPolygonRequest.Point getDefaultInstanceForType() {
        return io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.geoservice.InPolygonRequest.Point build() {
        io.grpc.geoservice.InPolygonRequest.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.geoservice.InPolygonRequest.Point buildPartial() {
        io.grpc.geoservice.InPolygonRequest.Point result = new io.grpc.geoservice.InPolygonRequest.Point(this);
        result.lat_ = lat_;
        result.lng_ = lng_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.geoservice.InPolygonRequest.Point) {
          return mergeFrom((io.grpc.geoservice.InPolygonRequest.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.geoservice.InPolygonRequest.Point other) {
        if (other == io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance()) return this;
        if (other.getLat() != 0F) {
          setLat(other.getLat());
        }
        if (other.getLng() != 0F) {
          setLng(other.getLng());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.geoservice.InPolygonRequest.Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.geoservice.InPolygonRequest.Point) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float lat_ ;
      /**
       * <code>float lat = 1;</code>
       */
      public float getLat() {
        return lat_;
      }
      /**
       * <code>float lat = 1;</code>
       */
      public Builder setLat(float value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float lat = 1;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0F;
        onChanged();
        return this;
      }

      private float lng_ ;
      /**
       * <code>float lng = 2;</code>
       */
      public float getLng() {
        return lng_;
      }
      /**
       * <code>float lng = 2;</code>
       */
      public Builder setLng(float value) {
        
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float lng = 2;</code>
       */
      public Builder clearLng() {
        
        lng_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:geoservice.InPolygonRequest.Point)
    }

    // @@protoc_insertion_point(class_scope:geoservice.InPolygonRequest.Point)
    private static final io.grpc.geoservice.InPolygonRequest.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.geoservice.InPolygonRequest.Point();
    }

    public static io.grpc.geoservice.InPolygonRequest.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      @java.lang.Override
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Point(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.geoservice.InPolygonRequest.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int POINT_FIELD_NUMBER = 1;
  private io.grpc.geoservice.InPolygonRequest.Point point_;
  /**
   * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
   */
  public boolean hasPoint() {
    return point_ != null;
  }
  /**
   * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
   */
  public io.grpc.geoservice.InPolygonRequest.Point getPoint() {
    return point_ == null ? io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance() : point_;
  }
  /**
   * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
   */
  public io.grpc.geoservice.InPolygonRequest.PointOrBuilder getPointOrBuilder() {
    return getPoint();
  }

  public static final int POLYGON_FIELD_NUMBER = 2;
  private java.util.List<io.grpc.geoservice.InPolygonRequest.Point> polygon_;
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  public java.util.List<io.grpc.geoservice.InPolygonRequest.Point> getPolygonList() {
    return polygon_;
  }
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  public java.util.List<? extends io.grpc.geoservice.InPolygonRequest.PointOrBuilder> 
      getPolygonOrBuilderList() {
    return polygon_;
  }
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  public int getPolygonCount() {
    return polygon_.size();
  }
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  public io.grpc.geoservice.InPolygonRequest.Point getPolygon(int index) {
    return polygon_.get(index);
  }
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  public io.grpc.geoservice.InPolygonRequest.PointOrBuilder getPolygonOrBuilder(
      int index) {
    return polygon_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (point_ != null) {
      output.writeMessage(1, getPoint());
    }
    for (int i = 0; i < polygon_.size(); i++) {
      output.writeMessage(2, polygon_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (point_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPoint());
    }
    for (int i = 0; i < polygon_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, polygon_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.geoservice.InPolygonRequest)) {
      return super.equals(obj);
    }
    io.grpc.geoservice.InPolygonRequest other = (io.grpc.geoservice.InPolygonRequest) obj;

    if (hasPoint() != other.hasPoint()) return false;
    if (hasPoint()) {
      if (!getPoint()
          .equals(other.getPoint())) return false;
    }
    if (!getPolygonList()
        .equals(other.getPolygonList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPoint()) {
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPoint().hashCode();
    }
    if (getPolygonCount() > 0) {
      hash = (37 * hash) + POLYGON_FIELD_NUMBER;
      hash = (53 * hash) + getPolygonList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.geoservice.InPolygonRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.geoservice.InPolygonRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.geoservice.InPolygonRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.geoservice.InPolygonRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code geoservice.InPolygonRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:geoservice.InPolygonRequest)
      io.grpc.geoservice.InPolygonRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.geoservice.InPolygonRequest.class, io.grpc.geoservice.InPolygonRequest.Builder.class);
    }

    // Construct using io.grpc.geoservice.InPolygonRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPolygonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pointBuilder_ == null) {
        point_ = null;
      } else {
        point_ = null;
        pointBuilder_ = null;
      }
      if (polygonBuilder_ == null) {
        polygon_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        polygonBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.geoservice.GeoServiceProto.internal_static_geoservice_InPolygonRequest_descriptor;
    }

    @java.lang.Override
    public io.grpc.geoservice.InPolygonRequest getDefaultInstanceForType() {
      return io.grpc.geoservice.InPolygonRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.geoservice.InPolygonRequest build() {
      io.grpc.geoservice.InPolygonRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.geoservice.InPolygonRequest buildPartial() {
      io.grpc.geoservice.InPolygonRequest result = new io.grpc.geoservice.InPolygonRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (pointBuilder_ == null) {
        result.point_ = point_;
      } else {
        result.point_ = pointBuilder_.build();
      }
      if (polygonBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          polygon_ = java.util.Collections.unmodifiableList(polygon_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.polygon_ = polygon_;
      } else {
        result.polygon_ = polygonBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.geoservice.InPolygonRequest) {
        return mergeFrom((io.grpc.geoservice.InPolygonRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.geoservice.InPolygonRequest other) {
      if (other == io.grpc.geoservice.InPolygonRequest.getDefaultInstance()) return this;
      if (other.hasPoint()) {
        mergePoint(other.getPoint());
      }
      if (polygonBuilder_ == null) {
        if (!other.polygon_.isEmpty()) {
          if (polygon_.isEmpty()) {
            polygon_ = other.polygon_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePolygonIsMutable();
            polygon_.addAll(other.polygon_);
          }
          onChanged();
        }
      } else {
        if (!other.polygon_.isEmpty()) {
          if (polygonBuilder_.isEmpty()) {
            polygonBuilder_.dispose();
            polygonBuilder_ = null;
            polygon_ = other.polygon_;
            bitField0_ = (bitField0_ & ~0x00000002);
            polygonBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPolygonFieldBuilder() : null;
          } else {
            polygonBuilder_.addAllMessages(other.polygon_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.geoservice.InPolygonRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.geoservice.InPolygonRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.grpc.geoservice.InPolygonRequest.Point point_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.geoservice.InPolygonRequest.Point, io.grpc.geoservice.InPolygonRequest.Point.Builder, io.grpc.geoservice.InPolygonRequest.PointOrBuilder> pointBuilder_;
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public boolean hasPoint() {
      return pointBuilder_ != null || point_ != null;
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.Point getPoint() {
      if (pointBuilder_ == null) {
        return point_ == null ? io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance() : point_;
      } else {
        return pointBuilder_.getMessage();
      }
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public Builder setPoint(io.grpc.geoservice.InPolygonRequest.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        point_ = value;
        onChanged();
      } else {
        pointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public Builder setPoint(
        io.grpc.geoservice.InPolygonRequest.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        point_ = builderForValue.build();
        onChanged();
      } else {
        pointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public Builder mergePoint(io.grpc.geoservice.InPolygonRequest.Point value) {
      if (pointBuilder_ == null) {
        if (point_ != null) {
          point_ =
            io.grpc.geoservice.InPolygonRequest.Point.newBuilder(point_).mergeFrom(value).buildPartial();
        } else {
          point_ = value;
        }
        onChanged();
      } else {
        pointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public Builder clearPoint() {
      if (pointBuilder_ == null) {
        point_ = null;
        onChanged();
      } else {
        point_ = null;
        pointBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.Point.Builder getPointBuilder() {
      
      onChanged();
      return getPointFieldBuilder().getBuilder();
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.PointOrBuilder getPointOrBuilder() {
      if (pointBuilder_ != null) {
        return pointBuilder_.getMessageOrBuilder();
      } else {
        return point_ == null ?
            io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance() : point_;
      }
    }
    /**
     * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.grpc.geoservice.InPolygonRequest.Point, io.grpc.geoservice.InPolygonRequest.Point.Builder, io.grpc.geoservice.InPolygonRequest.PointOrBuilder> 
        getPointFieldBuilder() {
      if (pointBuilder_ == null) {
        pointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.grpc.geoservice.InPolygonRequest.Point, io.grpc.geoservice.InPolygonRequest.Point.Builder, io.grpc.geoservice.InPolygonRequest.PointOrBuilder>(
                getPoint(),
                getParentForChildren(),
                isClean());
        point_ = null;
      }
      return pointBuilder_;
    }

    private java.util.List<io.grpc.geoservice.InPolygonRequest.Point> polygon_ =
      java.util.Collections.emptyList();
    private void ensurePolygonIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        polygon_ = new java.util.ArrayList<io.grpc.geoservice.InPolygonRequest.Point>(polygon_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.grpc.geoservice.InPolygonRequest.Point, io.grpc.geoservice.InPolygonRequest.Point.Builder, io.grpc.geoservice.InPolygonRequest.PointOrBuilder> polygonBuilder_;

    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public java.util.List<io.grpc.geoservice.InPolygonRequest.Point> getPolygonList() {
      if (polygonBuilder_ == null) {
        return java.util.Collections.unmodifiableList(polygon_);
      } else {
        return polygonBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public int getPolygonCount() {
      if (polygonBuilder_ == null) {
        return polygon_.size();
      } else {
        return polygonBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.Point getPolygon(int index) {
      if (polygonBuilder_ == null) {
        return polygon_.get(index);
      } else {
        return polygonBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder setPolygon(
        int index, io.grpc.geoservice.InPolygonRequest.Point value) {
      if (polygonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePolygonIsMutable();
        polygon_.set(index, value);
        onChanged();
      } else {
        polygonBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder setPolygon(
        int index, io.grpc.geoservice.InPolygonRequest.Point.Builder builderForValue) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.set(index, builderForValue.build());
        onChanged();
      } else {
        polygonBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder addPolygon(io.grpc.geoservice.InPolygonRequest.Point value) {
      if (polygonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePolygonIsMutable();
        polygon_.add(value);
        onChanged();
      } else {
        polygonBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder addPolygon(
        int index, io.grpc.geoservice.InPolygonRequest.Point value) {
      if (polygonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePolygonIsMutable();
        polygon_.add(index, value);
        onChanged();
      } else {
        polygonBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder addPolygon(
        io.grpc.geoservice.InPolygonRequest.Point.Builder builderForValue) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.add(builderForValue.build());
        onChanged();
      } else {
        polygonBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder addPolygon(
        int index, io.grpc.geoservice.InPolygonRequest.Point.Builder builderForValue) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.add(index, builderForValue.build());
        onChanged();
      } else {
        polygonBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder addAllPolygon(
        java.lang.Iterable<? extends io.grpc.geoservice.InPolygonRequest.Point> values) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, polygon_);
        onChanged();
      } else {
        polygonBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder clearPolygon() {
      if (polygonBuilder_ == null) {
        polygon_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        polygonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public Builder removePolygon(int index) {
      if (polygonBuilder_ == null) {
        ensurePolygonIsMutable();
        polygon_.remove(index);
        onChanged();
      } else {
        polygonBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.Point.Builder getPolygonBuilder(
        int index) {
      return getPolygonFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.PointOrBuilder getPolygonOrBuilder(
        int index) {
      if (polygonBuilder_ == null) {
        return polygon_.get(index);  } else {
        return polygonBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public java.util.List<? extends io.grpc.geoservice.InPolygonRequest.PointOrBuilder> 
         getPolygonOrBuilderList() {
      if (polygonBuilder_ != null) {
        return polygonBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(polygon_);
      }
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.Point.Builder addPolygonBuilder() {
      return getPolygonFieldBuilder().addBuilder(
          io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance());
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public io.grpc.geoservice.InPolygonRequest.Point.Builder addPolygonBuilder(
        int index) {
      return getPolygonFieldBuilder().addBuilder(
          index, io.grpc.geoservice.InPolygonRequest.Point.getDefaultInstance());
    }
    /**
     * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
     */
    public java.util.List<io.grpc.geoservice.InPolygonRequest.Point.Builder> 
         getPolygonBuilderList() {
      return getPolygonFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.grpc.geoservice.InPolygonRequest.Point, io.grpc.geoservice.InPolygonRequest.Point.Builder, io.grpc.geoservice.InPolygonRequest.PointOrBuilder> 
        getPolygonFieldBuilder() {
      if (polygonBuilder_ == null) {
        polygonBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.grpc.geoservice.InPolygonRequest.Point, io.grpc.geoservice.InPolygonRequest.Point.Builder, io.grpc.geoservice.InPolygonRequest.PointOrBuilder>(
                polygon_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        polygon_ = null;
      }
      return polygonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:geoservice.InPolygonRequest)
  }

  // @@protoc_insertion_point(class_scope:geoservice.InPolygonRequest)
  private static final io.grpc.geoservice.InPolygonRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.geoservice.InPolygonRequest();
  }

  public static io.grpc.geoservice.InPolygonRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InPolygonRequest>
      PARSER = new com.google.protobuf.AbstractParser<InPolygonRequest>() {
    @java.lang.Override
    public InPolygonRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InPolygonRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InPolygonRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InPolygonRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.geoservice.InPolygonRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

