// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geoservice.proto

package io.grpc.geoservice;

public interface InPolygonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoservice.InPolygonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();
}
