// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geotools.proto

package io.grpc.geotools;

public interface InPolygonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoservice.InPolygonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();

  /**
   * <code>string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
