// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geotools.proto

package io.grpc.geotools;

public interface InPolygonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:geoservice.InPolygonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
   */
  boolean hasPoint();
  /**
   * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
   */
  io.grpc.geotools.InPolygonRequest.Point getPoint();
  /**
   * <code>.geoservice.InPolygonRequest.Point point = 1;</code>
   */
  io.grpc.geotools.InPolygonRequest.PointOrBuilder getPointOrBuilder();

  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  java.util.List<io.grpc.geotools.InPolygonRequest.Point> 
      getPolygonList();
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  io.grpc.geotools.InPolygonRequest.Point getPolygon(int index);
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  int getPolygonCount();
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  java.util.List<? extends io.grpc.geotools.InPolygonRequest.PointOrBuilder> 
      getPolygonOrBuilderList();
  /**
   * <code>repeated .geoservice.InPolygonRequest.Point polygon = 2;</code>
   */
  io.grpc.geotools.InPolygonRequest.PointOrBuilder getPolygonOrBuilder(
      int index);
}
